### ISSUE TITLE
Inputs breaks if there are no obstacles

### ISSUE THREAD

**Issue by keegansmith21** [aubema/illumina#3]
When interpolating the obstacles, numpy's griddata breaks if the mask is empty or zero-filled. This can be fixed by adding a check inside the loop. For example:
`for i, mask in enumerate(defined):`
`if mask.astype(bool).any():`
`# Do stuff`

**Comment by aubema** [comment]
Thanks. We will check that

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: Keegan Smith ***@***.***>
Sent: Tuesday, April 19, 2022 9:37:21 PM
To: aubema/illumina ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aubema/illumina] Inputs breaks if there are no obstacles (Issue #3)


When interpolating the obstacles, numpy's griddata breaks if the mask is empty or zero-filled. This can be fixed by adding a check inside the loop. For example:
for i, mask in enumerate(defined):
if mask.astype(bool).any():
# Do stuff
